# Source: vcluster/templates/rbac/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-vcluster
  namespace: {{ .McNamespace }}
  labels:
    app: vcluster
    chart: "vcluster-0.15.2"
    release: "my-vcluster"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: vc-my-vcluster
    namespace: {{ .McNamespace }}
roleRef:
  kind: Role
  name: my-vcluster
  apiGroup: rbac.authorization.k8s.io