apiVersion: v1
kind: Service
metadata:
  name: vcluster-nodeport
  namespace: {{ .McNamespace }}
spec:
  selector:
    app: vcluster
    release: my-vcluster
  ports:
    - name: https
      port: 443
      targetPort: 8443
      # nodePort: 30950 #use for kind env. Please remove it when deploy in g5k vm
      protocol: TCP
  type: NodePort