# Source: vcluster/templates/workloadserviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-workload-my-vcluster
  namespace: {{ .McNamespace }}
  labels:
    app: vcluster
    chart: "vcluster-0.15.2"
    release: "my-vcluster"
    heritage: "Helm"