# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: {{ .McKlusterletName }}
spec:
  deployOption:
    mode: {{ .Vclustermode }}
  registrationImagePullSpec: {{ .Registry }}/registration:{{ .BundleVersion.RegistrationImageVersion }}
  workImagePullSpec: {{ .Registry }}/work:{{ .BundleVersion.RegistrationImageVersion }}  
  clusterName: {{ .ClusterName }}
  namespace: {{ .McNamespace }}
  externalServerURLs:
  {{ if .Klusterlet.APIServer }}
  - url: {{ .Klusterlet.APIServer }}
  {{ end }}
  {{if .RegistrationFeatures}}
  registrationConfiguration:
    featureGates:
    {{range .RegistrationFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{end}}
  {{end}}
  {{if .WorkFeatures}}
  workConfiguration:
    featureGates:
    {{range .WorkFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{end}}
  {{end}}
    # Uncomment the following configuration lines to add hostAliases for hub api server, 
    # if the server field in your hub cluster kubeconfig is a domain name instead of an ipv4 address.
    # For example, https://xxx.yyy.zzz.
    # This configuration is used for registration-agent and work-agent to communicate with hub api server.
  hubApiServerHostAlias:
    ip: "127.0.0.1"
    hostname: "localhost"
